import type { MockCase } from '@/lib/domain';

export const mockDatabase = {
  cases: [
    {
      caseId: 'CMP-2026-09001',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      channel: 'APP_CHAT_ESCALATION',
      receivedAt: '2026-08-15T10:26:00+08:00',
      rawText:
        '我8月12日在App提前结清，页面显示申请成功，今天还是扣了1248.36元。客服又说系统没结清，我有截图。请退回多扣的钱并确认不会影响征信，否则我会投诉监管。',
      status: 'PENDING_INVESTIGATION',
      expectedType: 'early_repayment_debit',
      expectedRiskLevel: 'MEDIUM',
      customerRequests: [
        '退回1248.36元',
        '确认贷款是否已经结清',
        '确认当前是否存在逾期或不良影响',
      ],
    },
    {
      caseId: 'CMP-2026-09002',
      customerId: 'CUST-1002',
      loanId: 'LOAN-3002',
      channel: 'HOTLINE',
      receivedAt: '2026-08-20T11:18:00+08:00',
      rawText:
        '今天还款时第一次一直转圈，我就重新点了一次，结果银行卡短信显示扣了两笔588.20元。请马上把重复的一笔退给我。',
      status: 'PENDING_INVESTIGATION',
      expectedType: 'duplicate_debit',
      expectedRiskLevel: 'MEDIUM',
      customerRequests: ['确认是否发生重复扣款', '退回多扣的一笔588.20元'],
    },
    {
      caseId: 'CMP-2026-09003',
      customerId: 'CUST-1003',
      loanId: null,
      channel: 'APP_SECURITY_ENTRY',
      receivedAt: '2026-08-28T08:06:00+08:00',
      rawText:
        '我昨晚一直在上海睡觉，凌晨有三笔我完全不认识的消费，共2578元。App还提示有新设备登录，这些都不是我操作的，请立刻处理。',
      status: 'PENDING_INVESTIGATION',
      expectedType: 'suspected_fraud',
      expectedRiskLevel: 'HIGH',
      customerRequests: [
        '核查三笔非本人交易',
        '阻止损失继续扩大',
        '说明后续处理路径',
      ],
    },
  ] satisfies MockCase[],
  customers: [
    {
      customerId: 'CUST-1001',
      maskedName: '林女士',
      accountStatus: 'ACTIVE',
      verificationLevel: 'FULL',
      usualLocation: '杭州',
      linkedLoanIds: ['LOAN-3001'],
      dataUpdatedAt: '2026-08-15T10:20:00+08:00',
    },
    {
      customerId: 'CUST-1002',
      maskedName: '周先生',
      accountStatus: 'ACTIVE',
      verificationLevel: 'FULL',
      usualLocation: '南京',
      linkedLoanIds: ['LOAN-3002'],
      dataUpdatedAt: '2026-08-20T11:10:00+08:00',
    },
    {
      customerId: 'CUST-1003',
      maskedName: '王先生',
      accountStatus: 'ACTIVE',
      verificationLevel: 'FULL',
      usualLocation: '上海',
      linkedLoanIds: [],
      dataUpdatedAt: '2026-08-28T08:00:00+08:00',
    },
  ],
  loans: [
    {
      loanId: 'LOAN-3001',
      customerId: 'CUST-1001',
      productType: 'CONSUMER_INSTALLMENT_LOAN',
      principal: 12000,
      termMonths: 12,
      contractStatus: 'SETTLED',
      settledAt: '2026-08-13T02:10:00+08:00',
      contractVersion: 'CONTRACT-CIL-2026.1',
      statusEvents: [
        {
          eventId: 'LOAN-3001-E7',
          occurredAt: '2026-08-13T02:10:00+08:00',
          fromStatus: 'EARLY_REPAYMENT_PROCESSING',
          toStatus: 'SETTLED',
          reason: '提前结清入账完成',
        },
      ],
      dataUpdatedAt: '2026-08-15T09:00:00+08:00',
    },
    {
      loanId: 'LOAN-3002',
      customerId: 'CUST-1002',
      productType: 'CONSUMER_INSTALLMENT_LOAN',
      principal: 6000,
      termMonths: 12,
      contractStatus: 'ACTIVE',
      settledAt: null,
      contractVersion: 'CONTRACT-CIL-2026.1',
      statusEvents: [],
      dataUpdatedAt: '2026-08-20T11:00:00+08:00',
    },
  ],
  schedules: [
    {
      scheduleId: 'SCHED-3001-06',
      loanId: 'LOAN-3001',
      installmentNumber: 6,
      dueDate: '2026-08-15',
      principal: 1190,
      interest: 58.36,
      fee: 0,
      total: 1248.36,
      status: 'CANCELLED_BY_SETTLEMENT',
      statusUpdatedAt: '2026-08-13T02:10:00+08:00',
    },
    {
      scheduleId: 'SCHED-3002-07',
      loanId: 'LOAN-3002',
      installmentNumber: 7,
      dueDate: '2026-08-20',
      principal: 550,
      interest: 38.2,
      fee: 0,
      total: 588.2,
      status: 'PAID',
      statusUpdatedAt: '2026-08-20T09:06:00+08:00',
    },
  ],
  transactions: [
    {
      transactionId: 'TXN-8101',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      relatedScheduleId: null,
      type: 'EARLY_REPAYMENT',
      amount: 9872.41,
      channel: 'UNIONPAY_WITHHOLDING',
      initiatedAt: '2026-08-12T09:45:00+08:00',
      completedAt: '2026-08-12T09:47:00+08:00',
      status: 'SUCCESS',
      channelReference: 'UP-ER-8101',
    },
    {
      transactionId: 'PAY-BATCH-815',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      relatedScheduleId: 'SCHED-3001-06',
      type: 'AUTOPAY_BATCH_INSTRUCTION',
      amount: 1248.36,
      channel: 'UNIONPAY_WITHHOLDING',
      initiatedAt: '2026-08-13T00:30:00+08:00',
      completedAt: null,
      status: 'QUEUED',
      channelReference: 'UP-BATCH-815',
    },
    {
      transactionId: 'CMD-815-R1',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      relatedScheduleId: 'SCHED-3001-06',
      type: 'AUTOPAY_REVOCATION',
      amount: 1248.36,
      channel: 'UNIONPAY_WITHHOLDING',
      initiatedAt: '2026-08-13T02:12:00+08:00',
      completedAt: '2026-08-13T02:42:00+08:00',
      status: 'TIMEOUT',
      channelReference: 'UP-REVOKE-815-R1',
    },
    {
      transactionId: 'TXN-8159',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      relatedScheduleId: 'SCHED-3001-06',
      type: 'SCHEDULED_DEBIT',
      amount: 1248.36,
      channel: 'UNIONPAY_WITHHOLDING',
      initiatedAt: '2026-08-15T07:12:00+08:00',
      completedAt: '2026-08-15T07:13:00+08:00',
      status: 'SUCCESS',
      channelReference: 'UP-DEBIT-8159',
    },
    {
      transactionId: 'TXN-8201',
      customerId: 'CUST-1002',
      loanId: 'LOAN-3002',
      relatedScheduleId: 'SCHED-3002-07',
      type: 'MANUAL_REPAYMENT',
      amount: 588.2,
      channel: 'BANK_CARD_PAYMENT',
      initiatedAt: '2026-08-20T09:02:00+08:00',
      completedAt: '2026-08-20T09:08:00+08:00',
      status: 'SUCCESS_AFTER_TIMEOUT',
      channelReference: 'BC-8201',
    },
    {
      transactionId: 'TXN-8202',
      customerId: 'CUST-1002',
      loanId: 'LOAN-3002',
      relatedScheduleId: 'SCHED-3002-07',
      type: 'MANUAL_REPAYMENT_RETRY',
      amount: 588.2,
      channel: 'BANK_CARD_PAYMENT',
      initiatedAt: '2026-08-20T09:05:00+08:00',
      completedAt: '2026-08-20T09:06:00+08:00',
      status: 'SUCCESS',
      channelReference: 'BC-8202',
    },
    {
      transactionId: 'REV-8201',
      customerId: 'CUST-1002',
      loanId: 'LOAN-3002',
      relatedScheduleId: 'SCHED-3002-07',
      type: 'AUTOMATIC_REVERSAL',
      amount: 588.2,
      channel: 'BANK_CARD_PAYMENT',
      initiatedAt: '2026-08-20T09:40:00+08:00',
      completedAt: null,
      status: 'PROCESSING',
      channelReference: 'BC-REV-8201',
    },
    {
      transactionId: 'TXN-8281',
      customerId: 'CUST-1003',
      loanId: null,
      relatedScheduleId: null,
      type: 'MERCHANT_PAYMENT',
      amount: 680,
      channel: 'WALLET',
      initiatedAt: '2026-08-28T01:14:00+08:00',
      completedAt: '2026-08-28T01:14:03+08:00',
      status: 'SUCCESS',
      channelReference: 'WL-8281',
    },
    {
      transactionId: 'TXN-8282',
      customerId: 'CUST-1003',
      loanId: null,
      relatedScheduleId: null,
      type: 'MERCHANT_PAYMENT',
      amount: 1299,
      channel: 'WALLET',
      initiatedAt: '2026-08-28T01:18:00+08:00',
      completedAt: '2026-08-28T01:18:04+08:00',
      status: 'SUCCESS',
      channelReference: 'WL-8282',
    },
    {
      transactionId: 'TXN-8283',
      customerId: 'CUST-1003',
      loanId: null,
      relatedScheduleId: null,
      type: 'MERCHANT_PAYMENT',
      amount: 599,
      channel: 'WALLET',
      initiatedAt: '2026-08-28T01:21:00+08:00',
      completedAt: '2026-08-28T01:21:02+08:00',
      status: 'SUCCESS',
      channelReference: 'WL-8283',
    },
  ],
  earlyRepaymentRequests: [
    {
      requestId: 'ER-9001',
      customerId: 'CUST-1001',
      loanId: 'LOAN-3001',
      submittedAt: '2026-08-12T09:42:00+08:00',
      quotedAmount: 9872.41,
      requestStatus: 'SETTLED',
      receiptText: '提前还款申请已提交，请关注后续处理结果。',
      paymentTransactionId: 'TXN-8101',
      settledAt: '2026-08-13T02:10:00+08:00',
    },
  ],
  tickets: [
    {
      ticketId: 'TKT-9001',
      customerId: 'CUST-1001',
      linkedCaseId: 'CMP-2026-09001',
      summary: '提前还款后仍被扣款，要求退回并核实贷款及逾期状态。',
    },
    {
      ticketId: 'TKT-9002',
      customerId: 'CUST-1002',
      linkedCaseId: 'CMP-2026-09002',
      summary: '还款重试后出现两笔相同扣款，要求立即退款。',
    },
    {
      ticketId: 'TKT-9003',
      customerId: 'CUST-1003',
      linkedCaseId: 'CMP-2026-09003',
      summary: '否认凌晨三笔交易，并报告新设备登录提示。',
    },
  ],
  securityEvents: [
    {
      eventId: 'SEC-8280',
      customerId: 'CUST-1003',
      occurredAt: '2026-08-28T01:09:00+08:00',
      eventType: 'NEW_DEVICE_LOGIN',
      deviceTrust: 'UNTRUSTED',
      deviceSummary: '首次出现的Android设备',
      locationSummary: '深圳',
      networkSummary: '非常用网络环境',
      riskSignals: ['NEW_DEVICE', 'LOCATION_DEVIATION', 'UNUSUAL_HOUR'],
      riskScoreBand: 'HIGH',
    },
    {
      eventId: 'SEC-8284',
      customerId: 'CUST-1003',
      occurredAt: '2026-08-28T01:22:00+08:00',
      eventType: 'TRANSACTION_BURST_ALERT',
      deviceTrust: 'UNTRUSTED',
      deviceSummary: '与SEC-8280相同设备',
      locationSummary: '深圳',
      networkSummary: '非常用网络环境',
      riskSignals: ['THREE_TRANSACTIONS_IN_EIGHT_MINUTES', 'AMOUNT_SPIKE'],
      riskScoreBand: 'HIGH',
    },
  ],
  rules: [
    {
      ruleId: 'RULE-REPAY-001',
      version: '2026.1',
      title: '提前还款状态解释规则',
      category: 'REPAYMENT',
      businessTypes: ['early_repayment_debit'],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'BUSINESS',
      clause:
        '前端显示申请已提交不代表核心账务已经结清，结清状态以核心贷款事件为准。',
      allowedDisposition: '核对核心账务状态后解释申请与结清的区别。',
      prohibitedClaims: ['仅凭申请回执认定已经结清'],
    },
    {
      ruleId: 'RULE-PAY-004',
      version: '2026.2',
      title: '结清后异常扣款处理规则',
      category: 'PAYMENT',
      businessTypes: ['early_repayment_debit'],
      effectiveFrom: '2026-07-01',
      effectiveTo: null,
      priority: 'BUSINESS',
      clause:
        '贷款结清后仍执行已取消应收计划的扣款，应标记为结清后异常扣款；核实成功流水和应收依据后可提交原路退回审批。',
      allowedDisposition: '生成原路退回建议并进入人工审批。',
      prohibitedClaims: ['未经审批声称已经退款'],
    },
    {
      ruleId: 'RULE-PAY-005',
      version: '2026.1',
      title: '重复扣款与在途冲正处理规则',
      category: 'PAYMENT',
      businessTypes: ['duplicate_debit'],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'BUSINESS',
      clause:
        '两笔交易指向同一应收项且均成功时需核查自动冲正，冲正在途期间不得重复提交人工退款。',
      allowedDisposition: '等待冲正完成或转支付团队核验。',
      prohibitedClaims: ['冲正在途时再次建议退款'],
    },
    {
      ruleId: 'RULE-APPROVAL-002',
      version: '2026.1',
      title: '异常扣款退回审批分级',
      category: 'APPROVAL',
      businessTypes: ['early_repayment_debit', 'duplicate_debit'],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'SAFETY',
      clause:
        '单笔异常扣款退回建议不超过2000元进入一级组长审批，超过2000元进入二级合规审批，AI不得直接执行。',
      allowedDisposition: '生成待审批建议。',
      prohibitedClaims: ['AI直接执行退款'],
    },
    {
      ruleId: 'RULE-CREDIT-003',
      version: '2026.1',
      title: '逾期与信用影响回复口径',
      category: 'CUSTOMER_COMMUNICATION',
      businessTypes: ['early_repayment_debit', 'duplicate_debit'],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'SAFETY',
      clause:
        '仅在账务和报送摘要未发现逾期事件时，可表述截至当前未发现逾期记录，不得承诺未来绝不产生影响。',
      allowedDisposition: '使用有时间边界的事实陈述。',
      prohibitedClaims: ['保证永不影响征信'],
    },
    {
      ruleId: 'RULE-SECURITY-001',
      version: '2026.2',
      title: '疑似未授权交易强制升级规则',
      category: 'ACCOUNT_SECURITY',
      businessTypes: ['suspected_fraud'],
      effectiveFrom: '2026-07-01',
      effectiveTo: null,
      priority: 'SAFETY',
      clause:
        '客户明确否认授权且存在新设备、地点偏离、异常时段或交易聚集信号时，案件必须升级账户安全团队。',
      allowedDisposition: '生成结构化安全转办包。',
      prohibitedClaims: ['确认盗刷已经成立', '声称账户已经冻结'],
    },
    {
      ruleId: 'RULE-SECURITY-002',
      version: '2026.1',
      title: '账户安全案件回复边界',
      category: 'ACCOUNT_SECURITY',
      businessTypes: ['suspected_fraud'],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'SAFETY',
      clause:
        '安全核验完成前只能确认受理和升级，不得认定交易性质、责任、追回或赔付结果。',
      allowedDisposition: '生成受理及转办说明。',
      prohibitedClaims: ['交易确定为盗刷', '资金一定追回'],
    },
    {
      ruleId: 'RULE-COMPLAINT-001',
      version: '2026.2',
      title: '投诉回复完整性规则',
      category: 'CUSTOMER_COMMUNICATION',
      businessTypes: [
        'early_repayment_debit',
        'duplicate_debit',
        'suspected_fraud',
      ],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'BUSINESS',
      clause:
        '对客回复只可在审批完成且结论、完成时间和执行时限明确后生成，不得披露内部审批或规则用语。',
      allowedDisposition: '审批结论字段齐备后生成对客草稿。',
      prohibitedClaims: ['审批完成前生成结论式回复', '披露内部审批用语'],
    },
    {
      ruleId: 'RULE-DATA-001',
      version: '2026.1',
      title: '案件调查最小数据使用规则',
      category: 'DATA_SAFETY',
      businessTypes: [
        'early_repayment_debit',
        'duplicate_debit',
        'suspected_fraud',
      ],
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      priority: 'SAFETY',
      clause: '调查工具只返回处理当前案件所需的脱敏字段和稳定记录ID。',
      allowedDisposition: '使用脱敏摘要和稳定记录ID。',
      prohibitedClaims: ['恢复或猜测被遮蔽的个人信息'],
    },
  ],
};
